apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  annotations:
    configmap.reloader.stakater.com/reload: "my-config"
spec:
  selector:
    matchLabels:
      app: busybox
      
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        resources: {}
        command:
          - sleep
          - "1000"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: my-config
      #restartPolicy: Never
   
